name: Update WidevineCdm
on:
  schedule:
    - cron: '0 17 * * *'   # Chạy lúc 0h sáng VN
  workflow_dispatch:

jobs:
  update:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Install 7z
      run: |
        choco install 7zip -y
    
    - name: Download and update
      shell: bash
      run: |
        # Get latest release URL for ungoogled-chromium
        URL=$(curl -s https://api.github.com/repos/macchrome/winchrome/releases | jq -r '[.[] | select(.prerelease == false)] | .[0] | .assets[] | select(.name | test("ungoogled-chromium-.*_Win64\\.7z$")) | .browser_download_url')
        
        # Download
        curl -L "$URL" -o ungoogled-chromium.7z
        
        # Extract using 7z
        7z x ungoogled-chromium.7z
        
        # Get new version
        NEW_VERSION=$(jq -r '.version' ungoogled-chromium-*/ungoogled-chromium-*/WidevineCdm/manifest.json)
        
        # Get current version
        CURRENT_VERSION=""
        if [ -f "WidevineCdm/manifest.json" ]; then
          CURRENT_VERSION=$(jq -r '.version' WidevineCdm/manifest.json)
        fi
        
        echo "Current: $CURRENT_VERSION"
        echo "New: $NEW_VERSION"
        
        # Update if different
        if [ "$NEW_VERSION" != "$CURRENT_VERSION" ]; then
          echo "Updating WidevineCdm..."
          rm -rf WidevineCdm
          cp -r "$DIR_NAME/$DIR_NAME/WidevineCdm" .
          
          git config user.name "GitHub Action"
          git config user.email "action@github.com"
          git add WidevineCdm/
          git commit -m "Update WidevineCdm to $NEW_VERSION"
          git push
        else
          echo "Already up to date"
        fi
