name: Update WidevineCdm

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  update-widevine:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
      
    - name: Download and update
      run: |
        # Download release mới nhất
        curl -s https://api.github.com/repos/bibicadotnet/microsoft-edge-multi-portable/releases \
        | jq -r '[.[] | select(.tag_name | contains("edge-canary-portable-x64"))] | .[0] | .assets[0].browser_download_url' \
        | xargs curl -L -o release.zip
        
        # Giải nén
        7z x release.zip
        
        # Tìm thư mục WidevineCdm trong Edge_Portable
        WIDEVINE_PATH=$(find . -path "*/Edge_Portable/Edge/*/WidevineCdm" -type d)
        
        # Đọc version mới
        NEW_VERSION=$(jq -r '.version' "$WIDEVINE_PATH/manifest.json")
        
        # Đọc version cũ
        if [ -f "WidevineCdm/manifest.json" ]; then
          OLD_VERSION=$(jq -r '.version' "WidevineCdm/manifest.json")
        else
          OLD_VERSION=""
        fi
        
        echo "Version cũ: $OLD_VERSION"
        echo "Version mới: $NEW_VERSION"
        
        # So sánh và update
        if [ "$NEW_VERSION" != "$OLD_VERSION" ]; then
          rm -rf WidevineCdm
          cp -r "$WIDEVINE_PATH" WidevineCdm
          
          git config user.name "GitHub Action"
          git config user.email "action@github.com"
          git add WidevineCdm/
          git commit -m "Update WidevineCdm to $NEW_VERSION"
          git push
          
          echo "Đã cập nhật lên $NEW_VERSION"
        else
          echo "Đã là version mới nhất"
        fi
