name: Update WidevineCdm

on:
  schedule:
    - cron: "0 * * * *"   # chạy mỗi giờ
  workflow_dispatch:      # cho phép chạy tay

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Download latest Edge Canary Portable
        run: |
          url=$(curl -s https://api.github.com/repos/bibicadotnet/microsoft-edge-multi-portable/releases/latest \
            | grep browser_download_url \
            | grep canary-portable-x64 \
            | cut -d '"' -f 4)
          echo "Download URL: $url"
          curl -L "$url" -o edge-canary.zip
          unzip -q edge-canary.zip -d edge-canary

      - name: Compare Widevine versions
        id: compare
        run: |
          NEW_MANIFEST=$(find edge-canary -path "*/WidevineCdm/manifest.json" | head -n1)
          OLD_MANIFEST="WidevineCdm/manifest.json"

          if [ ! -f "$NEW_MANIFEST" ]; then
            echo "Không tìm thấy manifest mới"
            exit 1
          fi

          new_version=$(jq -r '.version' "$NEW_MANIFEST")
          old_version=$(jq -r '.version' "$OLD_MANIFEST")

          echo "new_version=$new_version"
          echo "old_version=$old_version"

          if [ "$new_version" != "$old_version" ]; then
            echo "update_needed=true" >> $GITHUB_OUTPUT
            echo "new_version=$new_version" >> $GITHUB_OUTPUT
          else
            echo "update_needed=false" >> $GITHUB_OUTPUT
          fi

      - name: Update WidevineCdm
        if: steps.compare.outputs.update_needed == 'true'
        run: |
          NEW_WIDEVINE=$(dirname $(find edge-canary -path "*/WidevineCdm/manifest.json" | head -n1))
          rm -rf WidevineCdm
          cp -r "$NEW_WIDEVINE" ./WidevineCdm

      - name: Commit & push
        if: steps.compare.outputs.update_needed == 'true'
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add WidevineCdm
          git commit -m "Update WidevineCdm to version ${{
            steps.compare.outputs.new_version }}"
          git push
