name: Update WidevineCdm

on:
  schedule:
    - cron: '0 * * * *'  # Chạy mỗi giờ
  workflow_dispatch:  # Cho phép chạy thủ công

jobs:
  update-widevine:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Get latest release and download
      run: |
        # Lấy thông tin release mới nhất
        curl -s https://api.github.com/repos/bibicadotnet/microsoft-edge-multi-portable/releases \
          | jq -r '[.[] | select(.tag_name | contains("edge-canary-portable-x64"))] | .[0] | .assets[0].browser_download_url' \
          | xargs curl -L -o release.zip
        
        # Giải nén đơn giản
        7z x release.zip
        
        # Tìm thư mục WidevineCdm
        WIDEVINE_PATH=$(find . -name "WidevineCdm" -type d | head -1)
        
        if [ -z "$WIDEVINE_PATH" ]; then
          echo "Không tìm thấy thư mục WidevineCdm"
          exit 1
        fi
        
        echo "WIDEVINE_PATH=$WIDEVINE_PATH" >> $GITHUB_ENV
        
    - name: Check versions and update
      run: |
        # Đọc version mới
        NEW_VERSION=$(cat "$WIDEVINE_PATH/manifest.json" | jq -r '.version')
        
        # Đọc version hiện tại
        if [ -f "WidevineCdm/manifest.json" ]; then
          CURRENT_VERSION=$(cat "WidevineCdm/manifest.json" | jq -r '.version')
        else
          CURRENT_VERSION="không có"
        fi
        
        echo "Version hiện tại: $CURRENT_VERSION"
        echo "Version mới: $NEW_VERSION"
        
        if [ "$NEW_VERSION" != "$CURRENT_VERSION" ]; then
          echo "Cập nhật WidevineCdm..."
          rm -rf WidevineCdm
          cp -r "$WIDEVINE_PATH" WidevineCdm
          
          git config user.name "GitHub Action"
          git config user.email "action@github.com"
          git add WidevineCdm/
          git commit -m "Update WidevineCdm to $NEW_VERSION"
          git push
        else
          echo "Đã là version mới nhất rồi"
        fi
