name: Update WidevineCdm

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  update:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Download and update
      shell: bash
      run: |
        # Get latest release URL
        URL=$(curl -s https://api.github.com/repos/bibicadotnet/microsoft-edge-multi-portable/releases | jq -r '[.[] | select(.tag_name | contains("edge-canary-portable-x64"))] | .[0] | .assets[0].browser_download_url')
        
        # Download
        curl -L "$URL" -o edge.zip
        
        # Extract
        powershell -command "Expand-Archive -Path edge.zip -DestinationPath . -Force"
        
        # Get new version
        NEW_VERSION=$(jq -r '.version' Edge_Portable/Edge/*/WidevineCdm/manifest.json)
        
        # Get current version
        CURRENT_VERSION=""
        if [ -f "WidevineCdm/manifest.json" ]; then
          CURRENT_VERSION=$(jq -r '.version' WidevineCdm/manifest.json)
        fi
        
        echo "Current: $CURRENT_VERSION"
        echo "New: $NEW_VERSION"
        
        # Update if different
        if [ "$NEW_VERSION" != "$CURRENT_VERSION" ]; then
          echo "Updating WidevineCdm..."
          rm -rf WidevineCdm
          cp -r Edge_Portable/Edge/*/WidevineCdm .
          
          git config user.name "GitHub Action"
          git config user.email "action@github.com"
          git add WidevineCdm/
          git commit -m "Update WidevineCdm to $NEW_VERSION"
          git push
        else
          echo "Already up to date"
        fi
