name: Update WidevineCdm

on:
  schedule:
    - cron: '0 * * * *'  # Chạy mỗi giờ
  workflow_dispatch:  # Cho phép chạy thủ công

jobs:
  update-widevine:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Download and extract
      run: |
        # Lấy URL download
        DOWNLOAD_URL=$(curl -s https://api.github.com/repos/bibicadotnet/microsoft-edge-multi-portable/releases \
          | jq -r '[.[] | select(.tag_name | contains("edge-canary-portable-x64"))] | .[0] | .assets[0].browser_download_url')
        
        # Download và giải nén vào thư mục temp
        curl -L "$DOWNLOAD_URL" -o release.zip
        mkdir -p temp
        7z x release.zip -otemp
        
    - name: Check versions and update
      run: |
        # Debug: Xem cấu trúc thư mục
        echo "=== Cấu trúc thư mục temp ==="
        find temp -type f -name "*.json" | head -10
        echo "=== Tất cả thư mục ==="
        find temp -type d | head -20
        echo "=== Tìm WidevineCdm ==="
        find temp -name "*Widevine*" -o -name "*widevine*"
