name: Update WidevineCdm

on:
  schedule:
    - cron: '0 * * * *'  # Chạy mỗi giờ
  workflow_dispatch:  # Cho phép chạy thủ công

jobs:
  update-widevine:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Download and extract
      run: |
        # Lấy URL download
        DOWNLOAD_URL=$(curl -s https://api.github.com/repos/bibicadotnet/microsoft-edge-multi-portable/releases \
          | jq -r '[.[] | select(.tag_name | contains("edge-canary-portable-x64"))] | .[0] | .assets[0].browser_download_url')
        
        # Download và giải nén vào thư mục temp
        curl -L "$DOWNLOAD_URL" -o release.zip
        mkdir -p temp
        7z x release.zip -otemp
        
    - name: Check versions and update
      run: |
        # Tìm đường dẫn chính xác đến manifest.json
        MANIFEST_PATH=$(find temp -name "manifest.json" -path "*/WidevineCdm/*" | head -1)
        WIDEVINE_DIR=$(find temp -name "WidevineCdm" -type d | head -1)
        
        echo "Found manifest at: $MANIFEST_PATH"
        echo "Found WidevineCdm at: $WIDEVINE_DIR"
        
        # Đọc version mới
        NEW_VERSION=$(jq -r '.version' "$MANIFEST_PATH")
        
        # Đọc version hiện tại
        if [ -f "WidevineCdm/manifest.json" ]; then
          CURRENT_VERSION=$(jq -r '.version' WidevineCdm/manifest.json)
        else
          CURRENT_VERSION="không có"
        fi
        
        echo "Version hiện tại: $CURRENT_VERSION"
        echo "Version mới: $NEW_VERSION"
        
        if [ "$NEW_VERSION" != "$CURRENT_VERSION" ]; then
          echo "Cập nhật WidevineCdm..."
          rm -rf WidevineCdm
          cp -r "$WIDEVINE_DIR" .
          
          git config user.name "GitHub Action"
          git config user.email "action@github.com"
          git add WidevineCdm/
          git commit -m "Update WidevineCdm to $NEW_VERSION"
          git push
        else
          echo "Đã là version mới nhất rồi"
        fi
