name: Update WidevineCdm

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - run: |
        # Download
        curl -s https://api.github.com/repos/bibicadotnet/microsoft-edge-multi-portable/releases | jq -r '[.[] | select(.tag_name | contains("edge-canary-portable-x64"))] | .[0] | .assets[0].browser_download_url' | xargs curl -L -o edge.zip
        
        # Extract  
        7z x edge.zip
        
        # Get new version
        NEW=$(jq -r '.version' Edge_Portable/Edge/*/WidevineCdm/manifest.json)
        
        # Get old version
        OLD=""
        [ -f WidevineCdm/manifest.json ] && OLD=$(jq -r '.version' WidevineCdm/manifest.json)
        
        echo "Old: $OLD, New: $NEW"
        
        # Update if different
        if [ "$NEW" != "$OLD" ]; then
          rm -rf WidevineCdm
          cp -r Edge_Portable/Edge/*/WidevineCdm .
          git config user.name "bot"
          git config user.email "bot@github.com" 
          git add WidevineCdm
          git commit -m "Update WidevineCdm to $NEW"
          git push
        fi
